name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets/ios
        with:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install command line tools
        run: brew install swiftlint xcbeautify

      - name: SwiftLint
        run: |
          cd iosApp
          swiftlint

      - name: Build iOS App
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          cd iosApp
          set -o pipefail && xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -skipPackagePluginValidation \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            clean build | xcbeautify
