name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Verify & Build & E2E tests
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Checkout with secrets
        uses: ./.github/actions/checkout-with-secrets/ios
        with:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Install command line tools
        run: brew install swiftlint xcbeautify

      - name: SwiftLint
        run: |
          cd iosApp
          swiftlint

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.1.1'

      - name: Build iOS App
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          cd iosApp
          set -o pipefail && xcodebuild \
            -project iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -skipPackagePluginValidation \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            -derivedDataPath build \
            SYMROOT=$(pwd)/build \
            clean build | xcbeautify

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run e2e tests
        uses: futureware-tech/simulator-action@v4
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 300000 # 5 minutes for slow CI
        with:
          model: 'iPhone 17'
          os: 'iOS'
          wait_for_boot: true
      - run: |
          APP_PATH="$GITHUB_WORKSPACE/iosApp/build/Debug-iphonesimulator/HuKi.app"

          xcrun simctl install booted "$APP_PATH"

          maestro test .maestro/ -e APP_ID=hu.mostoha.mobile.ios.huki
